/**
 * GENERATED FILE — regenerated by `npm run check:palette` from the artist
 * sky-palette images committed at the repository root (6 sources found).
 *
 * Colors are sRGB hex sampled from the palette art (top half → zenith,
 * bottom half → horizon, warmest sample → sun). The time-of-day model
 * converts these into the working (linear) colour space at module load.
 */

export interface SkyPreset {
  zenith: string;
  horizon: string;
  sun: string;
}

export const SKY_PRESETS: Record<string, SkyPreset> = {
  "day": {
    "zenith": "#8f84f5",
    "horizon": "#c1a4fc",
    "sun": "#cfabfc"
  },
  "midnight": {
    "zenith": "#141452",
    "horizon": "#2f3bb7",
    "sun": "#445ae2"
  },
  "sunset": {
    "zenith": "#444d56",
    "horizon": "#a8302d",
    "sun": "#f9531f"
  },
  "turquoise": {
    "zenith": "#37484a",
    "horizon": "#7d8a81",
    "sun": "#8d9687"
  },
  "twilight": {
    "zenith": "#592461",
    "horizon": "#9a46a9",
    "sun": "#a64cb5"
  },
  "witherstorm": {
    "zenith": "#684e61",
    "horizon": "#a37a89",
    "sun": "#bf929e"
  }
};
