#!/usr/bin/env node
/**
 * Sky palette extraction (§27 asset pipeline).
 *
 * Reads the committed artist sky-palette images at the repository root and
 * derives zenith/horizon/sun colors (top-half mean, bottom-half mean, warmest
 * sample). Deterministic: no randomness, no dependencies beyond pngjs.
 * Output: src/config/skyPresets.generated.ts (idempotent regeneration).
 *
 * Run: npm run check:palette
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { PNG } from "pngjs";

const ROOT = process.cwd();

/** Candidate source images → preset name (first match wins).
 *  NOTE: the committed files contain literal '%20' in their names. */
const SOURCES = [
  { file: "skyday%20day (1).png", preset: "day" },
  { file: "sky%202%20midnight (1).png", preset: "midnight" },
  { file: "storymode_sky_sunset.png", preset: "sunset" },
  { file: "phase%205%20turquoise%20sky.png", preset: "turquoise" },
  { file: "phase5sky0purple%20sky.png", preset: "twilight" },
  { file: "phase6sky%206%20witherstorm.png", preset: "witherstorm" },
];

function decode(name) {
  const p = join(ROOT, name);
  if (!existsSync(p)) return null;
  return PNG.sync.read(readFileSync(p));
}

function averageRegion(png, y0, y1) {
  let r = 0, g = 0, b = 0, n = 0;
  const stride = Math.max(1, Math.floor(png.width / 64)); // sample grid
  for (let y = Math.floor(y0 * png.height); y < Math.floor(y1 * png.height); y++) {
    for (let x = 0; x < png.width; x += stride) {
      const idx = (png.width * y + x) << 2;
      r += png.data[idx];
      g += png.data[idx + 1];
      b += png.data[idx + 2];
      n++;
    }
  }
  if (n === 0) return [128, 128, 128];
  return [Math.round(r / n), Math.round(g / n), Math.round(b / n)];
}

function warmest(png) {
  let best = [255, 244, 214];
  let bestScore = -1;
  const stride = Math.max(1, Math.floor(png.width / 48));
  for (let y = 0; y < png.height; y += stride) {
    for (let x = 0; x < png.width; x += stride) {
      const idx = (png.width * y + x) << 2;
      const r = png.data[idx], g = png.data[idx + 1], b = png.data[idx + 2];
      const score = r * 1.6 + g * 0.9 - b * 0.7; // warmth heuristic
      if (score > bestScore) {
        bestScore = score;
        best = [r, g, b];
      }
    }
  }
  return best;
}

const hex = ([r, g, b]) =>
  "#" + [r, g, b].map((v) => Math.max(0, Math.min(255, v)).toString(16).padStart(2, "0")).join("");

const presets = {};
let used = 0;
for (const src of SOURCES) {
  const png = decode(src.file);
  if (!png) {
    console.warn(`  ~ skipped "${src.file}" (not found)`);
    continue;
  }
  const zenith = averageRegion(png, 0.05, 0.35);
  const horizon = averageRegion(png, 0.6, 0.95);
  const sun = warmest(png);
  presets[src.preset] = { zenith: hex(zenith), horizon: hex(horizon), sun: hex(sun) };
  used++;
  console.log(`  ✓ ${src.preset.padEnd(12)} zenith=${presets[src.preset].zenith} horizon=${presets[src.preset].horizon}`);
}

// Fallbacks for missing art keep the build reproducible.
const FALLBACK = {
  day: { zenith: "#3d7fd6", horizon: "#a8d4e8", sun: "#fff2d0" },
  midnight: { zenith: "#060a18", horizon: "#131c33", sun: "#b8c8ff" },
  sunset: { zenith: "#2a3a6e", horizon: "#ff8a4a", sun: "#ffd9a0" },
  turquoise: { zenith: "#0e8f8a", horizon: "#7de8d8", sun: "#e8fff8" },
  twilight: { zenith: "#1b1240", horizon: "#8a4a9e", sun: "#ff9ec4" },
  witherstorm: { zenith: "#11151c", horizon: "#2e3a4a", sun: "#8898a8" },
};
for (const [name, p] of Object.entries(FALLBACK)) {
  if (!presets[name]) presets[name] = p;
}

const out = `/**
 * GENERATED FILE — regenerated by \`npm run check:palette\` from the artist
 * sky-palette images committed at the repository root (${used} sources found).
 *
 * Colors are sRGB hex sampled from the palette art (top half → zenith,
 * bottom half → horizon, warmest sample → sun). The time-of-day model
 * converts these into the working (linear) colour space at module load.
 */

export interface SkyPreset {
  zenith: string;
  horizon: string;
  sun: string;
}

export const SKY_PRESETS: Record<string, SkyPreset> = ${JSON.stringify(presets, null, 2)};
`;

const target = join(ROOT, "src", "config", "skyPresets.generated.ts");
writeFileSync(target, out);
console.log(`palette extraction OK → ${target}`);
